### ISSUE TITLE
Missing repo quickstart sample app

### ISSUE THREAD

**Issue by Joncak** [pearsontechnology/deployment-pipeline-jenkins-plugin#4]
Hi there, its possible fix the sample app repo ? 

git@github.com:pearsontechnology/kubecon_docs.git not found.

**Comment by mward29** [comment]
I've open source the kubecon repos for you to peruse. You shouldn't however need them to be open to run the sample app as the user/password for RO of the git repos was supplied.
The kubecon_* repos were not open source simply because they were particular to kubecon. You'll want to modify the existing source code and tests repos for your own url if you want to use it.

**Comment by mward29** [comment]
@Joncak Hey mate, now that you can reach kubecon_docs, have you been able to get things up and running?

**Comment by Joncak** [comment]
@mward29 yeah working now, great work btw.

**Comment by mward29** [comment]
@Joncak let us know how we can improve. Would love your feedback.
